"""Add employee_number and qualification to Employee

Revision ID: c6121551a11f
Revises: f860803c48af
Create Date: 2026-02-17 16:37:36.481178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6121551a11f'
down_revision = 'f860803c48af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['employee_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('qualification')
        batch_op.drop_column('employee_number')

    # ### end Alembic commands ###
